name: Deploy

on:
    push:
        branches:
            - dev
            - MG-9/Fix-SSL
        
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        env:
            HEROKU_API_KEY: ${{secrets.HEROKU_1117419_API_KEY}}
        steps:
            - uses: actions/checkout@v2
            - run: |
                heroku auth:token
                heroku container:login
                docker build -t morskogram -f ./MorskoGram.Web.API/Dockerfile .
                docker tag morskogram registry.heroku.com/morskogram/web
                docker push registry.heroku.com/morskogram/web
                heroku container:release web -a morskogram